/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Datos.*;
import Modelo.*;
import javax.swing.JOptionPane;

/**
 *
 * @author zarel
 */
public class Practico extends javax.swing.JFrame {


   
    private Practicas practica;
    private static Estudiante estudiante;
    private ArchivoTextoProyectos archivoProyecto;
    private PropuestaProyecto propuestaProyecto;
    
    /**
     * Creates new form Practico
     */
    public Practico( Estudiante estudiante) {
        initComponents();
        this.setLocationRelativeTo(null);
       this.estudiante = estudiante;
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtAreaTrabajo = new javax.swing.JTextField();
        txtRepresentanteLegal = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtNombreEmpresa = new javax.swing.JTextField();
        txtFunciones = new javax.swing.JTextField();
        botonGuardar = new javax.swing.JButton();
        botonVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Tempus Sans ITC", 0, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("DATOS DE LAS PRACTICA");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 490, 67));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_multiply_30px.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 30, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 130));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel1.setText("Funciones a Realizar:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, 160, 40));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel2.setText("Nombre del lugar: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 130, 40));
        jPanel1.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 260, 40));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel3.setText("Direccion:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 100, 40));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel4.setText("Telefono:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 110, 50));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Representante Legal:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 150, 50));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel6.setText("Area de Trabajo:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 140, 50));
        jPanel1.add(txtAreaTrabajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, 260, 40));
        jPanel1.add(txtRepresentanteLegal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 260, 40));
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 260, 40));
        jPanel1.add(txtNombreEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 260, 40));
        jPanel1.add(txtFunciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 590, 260, 40));

        botonGuardar.setText("Guardar");
        botonGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonGuardarMouseClicked(evt);
            }
        });
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(botonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 660, 100, 30));

        botonVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_back_arrow_30px_1.png"))); // NOI18N
        botonVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonVolverMouseClicked(evt);
            }
        });
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });
        jPanel1.add(botonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 660, 50, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 698));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
       
        guardarPractica();
        
        this.estudiante=estudiante;
        archivoProyecto = new ArchivoTextoProyectos();
       
        
    }//GEN-LAST:event_botonGuardarActionPerformed

    public Practicas guardarPractica(){
        
        //LLENO LOS DATOS DE LAS PRACTICAS
        
        String nombreEmp, direccionEmp, telefonoEmp,repreLegal,areaTrbajo,funciones;
        
        nombreEmp = txtNombreEmpresa.getText().trim();
        direccionEmp = txtDireccion.getText().trim();
        telefonoEmp = txtTelefono.getText().trim();
        repreLegal = txtRepresentanteLegal.getText().trim();
        areaTrbajo = txtAreaTrabajo.getText().trim();
        funciones = txtFunciones.getText().trim();
        
        practica = new Practicas();
        
        practica.setNombreEmp(nombreEmp);
        practica.setDireccionEmp(direccionEmp);
        practica.setTelefonoEmp(telefonoEmp);
        practica.setRepreLegal(repreLegal);
        practica.setAreaTrbajo(areaTrbajo);
        practica.setFunciones(funciones);
        return practica;
    }
    
    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
      new Inicio().setVisible(true);
      dispose();
      
    }//GEN-LAST:event_botonVolverActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void botonGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGuardarMouseClicked
       //BOTON GUARDAR, PRACTICA, JENNY
        guardar();
       
    }//GEN-LAST:event_botonGuardarMouseClicked

    private void botonVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVolverMouseClicked
        regresar();
    }//GEN-LAST:event_botonVolverMouseClicked
  public void regresar(){   
      
      
      
        //     ****************FALTA BOTON REGRESAR*********
        
        
        
    }
      //JENNY
       private void guardar(){
           
       propuestaProyecto = new PropuestaProyecto();
       practica =guardarPractica();  
       propuestaProyecto= estudiante.getPropuesta();
       propuestaProyecto.setPracticas(practica);
       estudiante.setPropuesta(propuestaProyecto);
       
       guardarProyecto();
       
   }
    
     //JENNY
   public void guardarProyecto(){
        String mensaje="NO SE GUARDA ESA VAINA";
        
        try{
          mensaje = archivoProyecto.Guardar(estudiante);
           JOptionPane.showMessageDialog(this, mensaje,"GUARDO PROYECTO", JOptionPane.INFORMATION_MESSAGE); 
       }catch( Exception e){
           JOptionPane.showMessageDialog(this, e.getMessage() + mensaje, "ERROR AL GUARDAR PROYECTO", JOptionPane.ERROR_MESSAGE); 
         }
        
    }
    
    
    

  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Practico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Practico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Practico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Practico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Practico(estudiante).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtAreaTrabajo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtFunciones;
    private javax.swing.JTextField txtNombreEmpresa;
    private javax.swing.JTextField txtRepresentanteLegal;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
