/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Datos.ArchivoTextoProyectos;
import Modelo.*;
import javax.swing.JOptionPane;

/**
 *
 * @author zarel
 */
public class RegistrarTesis extends javax.swing.JFrame {

    private Tesis tesis ;
    private RegistrarProyecto registrarProyecto;
    private static Estudiante estudiante;
    private ArchivoTextoProyectos archivoProyecto = new ArchivoTextoProyectos();
    private PropuestaProyecto propuestaProyecto;
    
    /**
     * Creates new form Tesis
     */
    public  RegistrarTesis(Estudiante estudiante) {
        initComponents();
        this.setLocationRelativeTo(null);
        
       this.estudiante = estudiante; 
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtObjetivoGeneral = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtObjetivoEspecifico = new javax.swing.JTextField();
        txtJustificacion = new javax.swing.JTextField();
        txtPlanteamiento = new javax.swing.JTextField();
        botonGuardar = new javax.swing.JButton();
        jBotonDevolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Tempus Sans ITC", 0, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("DATOS DE LA TESIS");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 410, 67));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_multiply_30px.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 0, 30, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 90));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel1.setText("Planteamiento del problema:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 220, 30));
        jPanel1.add(txtObjetivoGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 1000, 80));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel2.setText("Justificacion:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 190, 30));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel3.setText("Objetivo General:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 190, 30));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel4.setText("Objetivo Especificos:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 190, 30));
        jPanel1.add(txtObjetivoEspecifico, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 1000, 90));
        jPanel1.add(txtJustificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 1000, 90));
        jPanel1.add(txtPlanteamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 1000, 80));

        botonGuardar.setText("Guardar");
        botonGuardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        botonGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonGuardarMouseClicked(evt);
            }
        });
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(botonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 680, 80, 30));

        jBotonDevolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_back_arrow_30px_1.png"))); // NOI18N
        jBotonDevolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBotonDevolverMouseClicked(evt);
            }
        });
        jBotonDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonDevolverActionPerformed(evt);
            }
        });
        jPanel1.add(jBotonDevolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 680, 40, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBotonDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonDevolverActionPerformed
      
    }//GEN-LAST:event_jBotonDevolverActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        
       guardarTesis();
        
    }//GEN-LAST:event_botonGuardarActionPerformed

    public Tesis guardarTesis(){
        
        //LLENO LOS DATOS DE LA TESIS
        
        String planteamientoproblema,objGeneral,objEspecifico,justificacion;
        
        planteamientoproblema = txtPlanteamiento.getText().trim();
        objGeneral = txtObjetivoGeneral.getText().trim();
        objEspecifico = txtObjetivoEspecifico.getText().trim();
        justificacion = txtJustificacion.getText().trim();
        
        tesis = new Tesis();
        
        tesis.setPlanteamientoproblema(planteamientoproblema);
        tesis.setObjGeneral(objGeneral);
        tesis.setObjEspecifico(objEspecifico);
        tesis.setJustificacion(justificacion);
        
        return tesis;
    }
    
    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jBotonDevolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBotonDevolverMouseClicked

    }//GEN-LAST:event_jBotonDevolverMouseClicked

    private void botonGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGuardarMouseClicked
     
       //BOTON GUARDAR, JENNY
       propuestaProyecto = new PropuestaProyecto();
       tesis = guardarTesis();
       propuestaProyecto = estudiante.getPropuesta();
       propuestaProyecto.setTesis(tesis);
       estudiante.setPropuesta(propuestaProyecto);

       guardarProyecto();
       
    }//GEN-LAST:event_botonGuardarMouseClicked

    public void NADITA(){
        
    }
    
    public void guardarProyecto(){
        String mensaje=".";
        
        try{
           
        mensaje = archivoProyecto.Guardar(estudiante);
           JOptionPane.showMessageDialog(this, mensaje, "GUARDO PROYECTO CORRECTAMENTE", JOptionPane.INFORMATION_MESSAGE); 
       }catch( Exception e){
           JOptionPane.showMessageDialog(this, e.getMessage() + mensaje, "ERROR AL GUARDAR PROYECTO", JOptionPane.ERROR_MESSAGE); 
         }
        
    }
    
    
    //HAGO UN METODO APARTE, POR SI ACASO, AL BORRAR EL BOTON NO SE ELIMINE LO QUE HICIMOS, JENNY
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarTesis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarTesis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarTesis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarTesis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarTesis(estudiante).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton jBotonDevolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtJustificacion;
    private javax.swing.JTextField txtObjetivoEspecifico;
    private javax.swing.JTextField txtObjetivoGeneral;
    private javax.swing.JTextField txtPlanteamiento;
    // End of variables declaration//GEN-END:variables
}
